class DEFINITIONS:
    BASIC_COLORING_AGENT = "BASIC"
    IMPROVED_COLORING_AGENT = "IMPROVED"
    IMPROVED_COLORING_AGENT_KD = "IMPROVED_KD"
    TEST = "TEST"
    BASIC_AGAINST_IMPROVED_AGENT = "BASIC-AGAINST-IMPROVED-AGENT"
    TEST_IMG_ASSETS_DIR = "/test-img-files/"
    RED = 0
    GREEN = 1
    BLUE = 2
    MAX_ITERATIONS = 1500
